repos:
  - repo: local
    hooks:
      - id: zig-fmt
        name: zig fmt
        entry: zig fmt
        language: system
        files: \.zig$
        pass_filenames: true
        stages: [pre-commit]
      - id: zig-fmt-check
        name: zig fmt check
        entry: zig fmt --check
        language: system
        files: \.zig$
        pass_filenames: true
        stages: [pre-commit]
